### ISSUE TITLE
Is this configurable this to work with private domains and self signed certificates?

### ISSUE THREAD

**Issue by wphesch-missionfocus** [BlackGlory/caddy-proxy#5]

**Comment by arnested** [comment]
Kind of.

You _can_ use your own, modified version of [`/etc/caddy-proxy/caddy.tmpl`](https://github.com/BlackGlory/caddy-proxy/blob/master/etc/caddy-proxy/caddy.tmpl) and add it on runtime via volumes.

**Comment by wphesch-missionfocus** [comment]
Thanks.

**Comment by BlackGlory** [comment]
@arnested has already answered your question, I just add more details.

As you described in the email, I think you should add "-http2=false" to CADDY_OPTIONS environment for turn off TLS, caddy-proxy will use CADDY_OPTIONS as CLI arguments. More help at https://caddyserver.com/docs/cli.

If you want separate caddyfile to a plurality of containers, you should build yourself caddy image, rather than use caddy-proxy to solve all problems. The philosophy of we creating caddy-proxy is similar as nginx-proxy, we will only use it as a reverse proxy server, avoid coupling between the containers, so the most of the time, you need to use your images to solve other problem.
